export enum RoleKey {
  home = "DEFAULT",
  awaiting_approval = "DEFAULT",
  notification = "DEFAULT",

  invoices = "BILL",

  report_revenue = "REPORT",
  report_product = "REPORT",
  report_inventory = "REPORT",
  report_sale = "REPORT",
  report_discount = "REPORT",
  report_employee = "REPORT",
  report_cashbook = "REPORT",

  list_product = "PRODUCT",
  menu = "PRODUCT",
  categories = "PRODUCT",

  list_employees = "EMPLOYEE",
  employees_role = "EMPLOYEE",
  timesheet = "EMPLOYEE",
  payroll = "EMPLOYEE",

  list_customers = "CUSTOMER",
  group_customer = "CUSTOMER",
  membership_card = "CUSTOMER",

  vouchers = "PROMOTION",

  pos = "DEFAULT",
  kds = "DEFAULT",

  stock_inventory = "INVENTORY",
  stock_in = "INVENTORY",
  stock_out = "INVENTORY",
  stock_check = "INVENTORY",
  history = "INVENTORY",
  partner_management = "INVENTORY",

  receipt = "TRANSACTION",
  payment_voucher = "TRANSACTION",
  profit_loss_accounting = "TRANSACTION",

  store = "DEFAULT",
  package_management = "DEFAULT",
  account_setup = "DEFAULT",
  online_support = "DEFAULT",
  logout = "DEFAULT",
  restaurant_info = "RESTAURANT_INFO",
}

export enum RoleLabel {
  home = "Tổng quan",
  invoices = "Hóa đơn",
  product = "Sản phẩm",
  list_product = "Danh sách sản phẩm",
  products_management = "Quản lý mặt hàng",
  empployees = "Nhân viên",
  list_employees = "Dánh sách nhân viên",
  customers = "Khách hàng",
  list_customers = "Danh sách khách hàng",
  vouchers = "Voucher",
  inventory = "Kho hàng",
  list_inventory = "Danh sách kho hàng",
  cashbook = "Sổ quỹ",
  store = "Thiết lập cửa hàng",
}

export const RoleKeyDefault = [
  {
    id: 1727,
    permission: {
      id: 1,
      name: "Tổng quan",
      key: "OVERVIEW",
    },
  },
];

export const ROLE_DEFAULT = {
  home: {
    all: false,
    read: false,
  },
  invoices: {
    all: false,
    read: false,
  },
  sale: {
    all: false,
    read: false,
  },
  product: {
    all: false,
    list_product: {
      all: false,
      read: false,
      create: false,
      update: false,
      delete: false,
    },
    import_product: {
      all: false,
      read: false,
      create: false,
      update: false,
      delete: false,
    },
    return_product: {
      all: false,
      read: false,
      create: false,
      update: false,
      delete: false,
    },
    check_inventory: {
      all: false,
      read: false,
      create: false,
      update: false,
      delete: false,
    },
    price_setting: {
      all: false,
      read: false,
      create: false,
      update: false,
      delete: false,
    },
  },
  market: {
    all: false,
    market_common: {
      all: false,
      read: false,
      create: false,
      update: false,
      delete: false,
    },
    market_store: {
      all: false,
      read: false,
      create: false,
      update: false,
      delete: false,
    },
    market_setting: {
      all: false,
      read: false,
      create: false,
      update: false,
      delete: false,
    },
  },
  medicine_category: {
    all: false,
    read: false,
    create: false,
    update: false,
    delete: false,
  },
  transaction: {
    all: false,
    bill: {
      all: false,
      read: false,
      create: false,
      update: false,
      delete: false,
    },
    order: {
      all: false,
      read: false,
      create: false,
      update: false,
      delete: false,
    },
    return: {
      all: false,
      read: false,
      create: false,
      update: false,
      delete: false,
    },
    delivery: {
      all: false,
      read: false,
      create: false,
      update: false,
      delete: false,
    },
  },
  partner: {
    all: false,
    customer: {
      all: false,
      read: false,
      create: false,
      update: false,
      delete: false,
    },
    group_customer: {
      all: false,
      read: false,
      create: false,
      update: false,
      delete: false,
    },
    provider: {
      all: false,
      read: false,
      create: false,
      update: false,
      delete: false,
    },
    group_provider: {
      all: false,
      read: false,
      create: false,
      update: false,
      delete: false,
    },
    doctor: {
      all: false,
      read: false,
      create: false,
      update: false,
      delete: false,
    },
  },
  cashbook: {
    all: false,
    read: false,
    create: false,
    update: false,
    delete: false,
  },

  report: {
    all: false,
    customer_report: {
      all: false,
      read: false,
      create: false,
      update: false,
      delete: false,
    },
    provider_report: {
      all: false,
      read: false,
      create: false,
      update: false,
      delete: false,
    },
    employee_report: {
      all: false,
      read: false,
      create: false,
      update: false,
      delete: false,
    },
    sale_report: {
      all: false,
      read: false,
      create: false,
      update: false,
      delete: false,
    },
    product_report: {
      all: false,
      read: false,
      create: false,
      update: false,
      delete: false,
    },
  },
  setting: {
    all: false,
    store: {
      all: false,
      read: false,
      create: false,
      update: false,
      delete: false,
    },
    branch: {
      all: false,
      read: false,
      create: false,
      update: false,
      delete: false,
    },
    employee: {
      all: false,
      read: false,
      create: false,
      update: false,
      delete: false,
    },
    role: {
      all: false,
      read: false,
      create: false,
      update: false,
      delete: false,
    },
    discount: {
      all: false,
      read: false,
      create: false,
      update: false,
      delete: false,
    },
    point_setting: {
      all: false,
      read: false,
      create: false,
      update: false,
      delete: false,
    },
    connect_system: {
      all: false,
      read: false,
      create: false,
      update: false,
      delete: false,
    },
    delivery_fee: {
      all: false,
      read: false,
      create: false,
      update: false,
      delete: false,
    },
    connect_delivery: {
      all: false,
      read: false,
      create: false,
      update: false,
      delete: false,
    },
  },
};
